name: 系统日志异常检测
version: "1.0.0"
description: 日志解析、异常检测算法、告警集成和故障分析
created_at: "2026-02-11T14:40:00"
source: "改编自sim工作流模板库"
category: "monitoring"
tags: ["monitoring", "logs", "anomaly-detection", "alerting", "devops"]
triggers:
  - "日志检测"
  - "异常检测"
  - "监控告警"
  - "log analysis"
steps:
  - id: 1
    name: 获取系统日志
    action: run_command
    params:
      command: "echo 获取最新系统日志..."
      save_as: system_logs
      timeout: 10

  - id: 2
    name: 解析日志格式
    action: run_command
    params:
      command: "echo 解析日志格式和结构..."
      save_as: parsed_logs
      timeout: 10

  - id: 3
    name: 异常检测分析
    action: run_command
    params:
      command: "echo 使用AI检测异常模式..."
      save_as: anomalies_detected
      timeout: 20

  - id: 4
    name: 生成告警
    action: run_command
    params:
      command: "echo 生成告警通知..."
      save_as: alerts
      timeout: 5

  - id: 5
    name: 生成分析报告
    action: generate_document
    params:
      template: "log-analysis.md"
      variables:
        logs: "{{parsed_logs}}"
        anomalies: "{{anomalies_detected}}"
        alerts: "{{alerts}}"
        date: "{{current_date}}"
      output: "docs/log-analysis-{{current_date}}.md"
      save_as: analysis_report

  - id: 6
    name: 输出检测结果
    action: notify
    params:
      message: |
        日志异常检测完成！
        检测到异常: {{anomalies_detected}}
        生成告警: {{alerts}}
        分析报告: {{analysis_report}}
