name: 会议记录自动整理
version: "1.0.0"
description: 自动整理会议纪要，提取行动项并分配给责任人
created_at: "2026-02-11T14:20:00"
source: "改编自sim工作流模板库"
category: "documentation"
tags: ["meeting", "minutes", "documentation", "automation", "action-items"]
triggers:
  - "整理会议"
  - "会议纪要"
  - "meeting minutes"
  - "会议记录"
steps:
  - id: 1
    name: 获取会议录音/笔记
    action: run_command
    params:
      command: "echo 获取会议录音或原始笔记..."
      save_as: meeting_raw
      timeout: 5

  - id: 2
    name: 转录和摘要
    action: run_command
    params:
      command: "echo 使用AI转录并生成摘要..."
      save_as: meeting_summary
      timeout: 15

  - id: 3
    name: 提取行动项
    action: run_command
    params:
      command: "echo 提取行动项和责任人..."
      save_as: action_items
      timeout: 10

  - id: 4
    name: 识别决策点
    action: run_command
    params:
      command: "echo 识别会议中的关键决策..."
      save_as: decisions
      timeout: 5

  - id: 5
    name: 生成结构化纪要
    action: generate_document
    params:
      template: "meeting-minutes.md"
      variables:
        summary: "{{meeting_summary}}"
        actions: "{{action_items}}"
        decisions: "{{decisions}}"
        date: "{{current_date}}"
      output: "docs/meeting-minutes-{{current_date}}.md"
      save_as: minutes_file

  - id: 6
    name: 完成通知
    action: notify
    params:
      message: |
        会议纪要整理完成！
        摘要: {{meeting_summary}}
        行动项: {{action_items}}
        决策点: {{decisions}}
        完整纪要: {{minutes_file}}
