name: 真正的自动化示例
version: "2.0.0"
description: 展示E-V-H三阶段闭环的真正自动化工作流，零确认执行+自动验证+自愈修复
category: "automation"
tags: ["auto-verify", "self-healing", "zero-confirmation"]

triggers:
  - "自动化示例"
  - "auto demo"
  - "演示自动化"

steps:
  - id: 1
    name: 创建输出目录
    action: run_command
    params:
      command: "python -c \"import os; os.makedirs('output', exist_ok=True)\""
      timeout: 5

  - id: 2
    name: 创建测试模块
    action: run_command
    params:
      command: "python -c \"open('output/test_module.py','w',encoding='utf-8').write('def hello():\\n    return \\\"Hello, World!\\\"\\n\\ndef add(a, b):\\n    return a + b\\n')\""
      timeout: 10

  - id: 3
    name: 验证文件创建
    action: verify
    type: file_exists
    path: "output/test_module.py"
    fail_message: "模块文件未创建成功"

  - id: 4
    name: 验证模块可导入
    action: verify
    type: command_success
    command: "python -c \"import sys; sys.path.insert(0,'output'); from test_module import hello,add; assert hello()=='Hello, World!'; assert add(1,2)==3\""
    fail_message: "模块导入或功能验证失败"
    timeout: 15

  - id: 5
    name: 创建测试文件
    action: run_command
    params:
      command: "python -c \"open('output/test_module_test.py','w',encoding='utf-8').write('import sys\\nsys.path.insert(0,\\\"output\\\")\\nfrom test_module import hello,add\\nassert hello()==\\\"Hello, World!\\\"\\nassert add(1,2)==3\\nprint(\\\"测试通过\\\")\\n')\""
      timeout: 10

  - id: 6
    name: 验证测试文件创建
    action: verify
    type: file_exists
    path: "output/test_module_test.py"
    fail_message: "测试文件未创建成功"

  - id: 7
    name: 运行测试
    action: verify
    type: test_pass
    command: "python output/test_module_test.py"
    fail_message: "测试未通过"
    timeout: 15

  - id: 8
    name: 创建JSON配置
    action: run_command
    params:
      command: "python -c \"import json; open('output/config.json','w',encoding='utf-8').write(json.dumps({'module':'test_module','version':'1.0.0','tested':True},indent=2))\""

  - id: 9
    name: 验证JSON格式
    action: verify
    type: json_valid
    path: "output/config.json"
    fail_message: "JSON格式无效"

  - id: 10
    name: 验证JSON内容
    action: verify
    type: content_assert
    file: "output/config.json"
    contains: ["module", "version", "tested"]
    fail_message: "JSON缺少必要字段"

  - id: 11
    name: 生成报告
    action: generate_document
    params:
      output: "output/automation-report.md"
      content: |
        # 自动化执行报告
        
        **生成时间**: {{current_date}} {{current_time}}
        
        ## 执行结果
        
        | 步骤 | 状态 |
        |------|------|
        | 创建模块 | ✅ 完成 |
        | 验证文件 | ✅ 通过 |
        | 验证导入 | ✅ 通过 |
        | 创建测试 | ✅ 完成 |
        | 运行测试 | ✅ 通过 |
        | 创建配置 | ✅ 完成 |
        | 验证JSON | ✅ 通过 |
        
        ## 生成的文件
        
        - `output/test_module.py` - 主模块
        - `output/test_module_test.py` - 测试文件
        - `output/config.json` - 配置文件
        - `output/automation-report.md` - 本报告
        
        ## 验证摘要
        
        所有验证步骤均已通过，无需人工干预。

  - id: 12
    name: 最终验证
    action: verify
    type: file_exists
    path: "output/automation-report.md"
    fail_message: "报告文件未生成"

  - id: 13
    name: 输出结果
    action: notify
    params:
      message: |
        ✅ 自动化工作流执行完成！
        
        验证结果：
        - 模块文件: 已创建并验证
        - 测试文件: 已创建并通过测试
        - 配置文件: 已创建并验证JSON格式
        - 报告文件: 已生成
        
        所有步骤均已自动执行，无需人工确认。
        查看报告: output/automation-report.md
