name: Git提交摘要
description: 自动获取最近git提交记录并生成摘要文档
version: "2.0.0"
created_at: "2026-02-11T11:00:00"
triggers:
  - "生成提交摘要"
  - "git summary"
  - "周报"

steps:
  - id: 1
    name: 创建输出目录
    action: run_command
    params:
      command: "mkdir -p output"
      timeout: 5

  - id: 2
    name: 获取Git提交记录
    action: run_command
    params:
      command: "git log --since='1 week ago' --pretty=format:'%h - %s (%ar)' --no-merges -20"
      save_as: git_commits
      timeout: 10

  - id: 3
    name: 获取代码统计
    action: run_command
    params:
      command: "git diff --shortstat HEAD~10..HEAD"
      save_as: git_stats
      timeout: 10

  - id: 4
    name: 生成摘要文档
    action: generate_document
    params:
      output: "output/git-summary-{{current_date}}.md"
      content: |
        # Git提交摘要
        
        **生成时间**: {{current_date}} {{current_time}}
        
        ## 最近提交
        
        {{git_commits}}
        
        ## 代码变更统计
        
        {{git_stats}}
        
        ---
        *由 Trae 自动生成*

  - id: 5
    name: 完成通知
    action: notify
    params:
      message: "✅ Git提交摘要已生成！报告: output/git-summary-{{current_date}}.md"